<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="191950" started-at="2022-01-06T20:03:16Z" finished-at="2022-01-06T20:06:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="191950" started-at="2022-01-06T20:03:16Z" finished-at="2022-01-06T20:06:28Z">
      <class name="com.qa.toolsqa.TestCases.LoginPageTest">
        <test-method status="PASS" signature="extentreport()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="extentreport" is-config="true" duration-ms="1366" started-at="2022-01-07T01:33:15Z" finished-at="2022-01-07T01:33:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentreport -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="setup" is-config="true" duration-ms="120149" started-at="2022-01-07T01:33:16Z" finished-at="2022-01-07T01:35:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="checkfail()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="checkfail" duration-ms="52" started-at="2022-01-07T01:35:16Z" finished-at="2022-01-07T01:35:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkfail -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="getResult" is-config="true" duration-ms="1560" started-at="2022-01-07T01:35:16Z" finished-at="2022-01-07T01:35:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkfail status=SUCCESS method=LoginPageTest.checkfail()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="setup" is-config="true" duration-ms="35086" started-at="2022-01-07T01:35:18Z" finished-at="2022-01-07T01:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="loginTest" duration-ms="1238" started-at="2022-01-07T01:35:53Z" finished-at="2022-01-07T01:35:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.qa.toolsqa.TestCases.LoginPageTest.loginTest(LoginPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="getResult" is-config="true" duration-ms="845" started-at="2022-01-07T01:35:54Z" finished-at="2022-01-07T01:35:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginPageTest.loginTest()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.toolsqa.TestCases.LoginPageTest@67784306]" name="teardown" is-config="true" duration-ms="1022" started-at="2022-01-07T01:36:28Z" finished-at="2022-01-07T01:36:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.toolsqa.TestCases.LoginPageTest -->
      <class name="com.qa.toolsqa.TestCases.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.toolsqa.TestCases.HomePageTest@335eadca]" name="setup" is-config="true" duration-ms="30782" started-at="2022-01-07T01:35:55Z" finished-at="2022-01-07T01:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyusername()[pri:0, instance:com.qa.toolsqa.TestCases.HomePageTest@335eadca]" name="verifyusername" duration-ms="915" started-at="2022-01-07T01:36:26Z" finished-at="2022-01-07T01:36:27Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<teston[r]e> but was:<teston[]e>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<teston[r]e> but was:<teston[]e>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.qa.toolsqa.TestCases.HomePageTest.verifyusername(HomePageTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyusername -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.qa.toolsqa.TestCases.HomePageTest@335eadca]" name="getResult" is-config="true" duration-ms="1245" started-at="2022-01-07T01:36:27Z" finished-at="2022-01-07T01:36:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyusername status=FAILURE method=HomePageTest.verifyusername()[pri:0, instance:com.qa.toolsqa.TestCases.HomePageTest@335eadca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.qa.toolsqa.TestCases.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
